### ISSUE TITLE
There may be some typos

### ISSUE THREAD

**Issue by UESTCht** [center-for-threat-informed-defense/insider-threat-ttp-kb#2]
There may be some typos on Page 13 of [design-principles-and-methodology.pdf](https://github.com/center-for-threat-informed-defense/insider-threat-ttp-kb/blob/main/design-principles-and-methodology.pdf?raw=true).

![image](https://user-images.githubusercontent.com/103543710/163075441-aefd6b1c-19d0-4ba1-a75c-b5f76cacc867.png)
I think the "T1306" should be "T1036", and "T1572" should be "T1562".

Is that so？

**Comment by mehaase** [comment]
In version 2.0 we have removed the design principles document and migrated that content onto the website. I confirmed that Masquerading is correctly labeled as T1036. Also T1562 and T1572 are correctly wherever they are used. thank you for reporting this.
