### ISSUE TITLE
Enforcing maxValue > minValue ATT&CK Navigator specification

### ISSUE THREAD

**Issue by IanDavila** [center-for-threat-informed-defense/insider-threat-ttp-kb#4]
**Describe the bug**
The Insider Threat TTP Knowledge Base navigator layer currently has maxValue == minValue to 1 and the Navigator Layer format definition states that the maxValue should be greater than the minValue. Here is the current navigator spec: https://github.com/mitre-attack/attack-navigator/blob/master/layers/LAYERFORMATv4_5.md

**Comment by mehaase** [comment]
Thank you for catching this @IanDavila. We'll fix up the layers shortly.

**Comment by IanDavila** [comment]
thanks @mehaase!
